include ../../config.mk

module_dirs=dumb udp_helper

all:
	for d in $(module_dirs) ; do \
		make -C $$d $@;	\
	done

headers:
	for d in $(module_dirs) ; do \
		make -C $$d $@;	\
	done

install:
	for d in $(module_dirs) ; do \
		make -C $$d $@;	\
	done

clean:
	for d in $(module_dirs) ; do \
		make -C $$d $@;	\
	done

