/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol_def.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol_def.pb-c.h"
void   msg_est__init
                     (MsgEst         *message)
{
  static MsgEst init_value = MSG_EST__INIT;
  *message = init_value;
}
size_t msg_est__get_packed_size
                     (const MsgEst *message)
{
  assert(message->base.descriptor == &msg_est__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_est__pack
                     (const MsgEst *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_est__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_est__pack_to_buffer
                     (const MsgEst *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_est__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgEst *
       msg_est__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgEst *)
     protobuf_c_message_unpack (&msg_est__descriptor,
                                allocator, len, data);
}
void   msg_est__free_unpacked
                     (MsgEst *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &msg_est__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_notify__init
                     (MsgNotify         *message)
{
  static MsgNotify init_value = MSG_NOTIFY__INIT;
  *message = init_value;
}
size_t msg_notify__get_packed_size
                     (const MsgNotify *message)
{
  assert(message->base.descriptor == &msg_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_notify__pack
                     (const MsgNotify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_notify__pack_to_buffer
                     (const MsgNotify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgNotify *
       msg_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgNotify *)
     protobuf_c_message_unpack (&msg_notify__descriptor,
                                allocator, len, data);
}
void   msg_notify__free_unpacked
                     (MsgNotify *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &msg_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   api__init
                     (API         *message)
{
  static API init_value = API__INIT;
  *message = init_value;
}
size_t api__get_packed_size
                     (const API *message)
{
  assert(message->base.descriptor == &api__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t api__pack
                     (const API *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &api__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t api__pack_to_buffer
                     (const API *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &api__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
API *
       api__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (API *)
     protobuf_c_message_unpack (&api__descriptor,
                                allocator, len, data);
}
void   api__free_unpacked
                     (API *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &api__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_est__field_descriptors[1] =
{
  {
    "session_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MsgEst, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_est__field_indices_by_name[] = {
  0,   /* field[0] = session_id */
};
static const ProtobufCIntRange msg_est__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg_est__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Msg_est",
  "MsgEst",
  "MsgEst",
  "",
  sizeof(MsgEst),
  1,
  msg_est__field_descriptors,
  msg_est__field_indices_by_name,
  1,  msg_est__number_ranges,
  (ProtobufCMessageInit) msg_est__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_notify__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MsgNotify, type),
    &notify_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_notify__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange msg_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg_notify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Msg_notify",
  "MsgNotify",
  "MsgNotify",
  "",
  sizeof(MsgNotify),
  1,
  msg_notify__field_descriptors,
  msg_notify__field_indices_by_name,
  1,  msg_notify__number_ranges,
  (ProtobufCMessageInit) msg_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor api__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(API, type),
    &notify_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned api__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange api__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor api__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "API",
  "API",
  "API",
  "",
  sizeof(API),
  1,
  api__field_descriptors,
  api__field_indices_by_name,
  1,  api__number_ranges,
  (ProtobufCMessageInit) api__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue notify_type__enum_values_by_number[2] =
{
  { "Message", "NOTIFY_TYPE__Message", 0 },
  { "Session", "NOTIFY_TYPE__Session", 1 },
};
static const ProtobufCIntRange notify_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex notify_type__enum_values_by_name[2] =
{
  { "Message", 0 },
  { "Session", 1 },
};
const ProtobufCEnumDescriptor notify_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NotifyType",
  "NotifyType",
  "NotifyType",
  "",
  2,
  notify_type__enum_values_by_number,
  2,
  notify_type__enum_values_by_name,
  1,
  notify_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
